
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: auth-server.demoback.chasemoskal.com
    http:
      paths:
      - backend:
          serviceName: auth-server
          servicePort: 8000
  - host: profile-server.demoback.chasemoskal.com
    http:
      paths:
      - backend:
          serviceName: profile-server
          servicePort: 8001
