
apiVersion: v1
kind: Service
metadata:
  name: demoback-service
spec:
  type: LoadBalancer
  ports:
  - name: auth-server
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: profile-server
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: demoback
